muscle_app/urls.py
from . import views
from django.conf.urls.static import static
from django.conf import settings

from django.urls import path
from django.contrib.auth import views as auth_views


app_name= 'muscle_app'

urlpatterns = [
    path('', views.index_view, name='index'),

    # ユーザー関連
    # 新規登録
    path('sign_up', views.SignUp.as_view(), name='sign_up'),
    # ログイン
    path('login', views.Login.as_view(), name='login'),
    # ログアウト
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # マイページ
    path('mypage', views.mypage_view, name='mypage'),
    # ユーザー情報詳細
    path('user_detail/<str:user_id>', views.user_detail, name='user_detail'),
    # ユーザー情報の変更
    path('user_update', views.UserUpdate.as_view(), name='user_update'),
    # path('user_update', views.user_update, name='user_update'),
    # パスワードの変更
    path('password_change', views.PasswordChange.as_view(), name='password_change'),
    # パスワードの変更に成功した場合に表示表示
    path('password_change/done', views.PasswordChangeDone.as_view(), name='password_done'),

    # 記事関連
    # markはマークダウンでの登録画面の呼び出し
    path('mark', views.mark_view, name='mark'),
    # mark_insertは登録したことを通知
    path('mark_insert', views.mark_insert_view, name='mark_insert'),
    # mark_listはタイトルとユーザー名を表示した一覧画面
    path('mark_list', views.mark_list_views, name='mark_list'),
    # 部位ごとに記事を絞り込んで表示
    path('parts/<str:category>', views.parts_view, name='parts'),
    # 検索ボックスで検索した内容を絞り込んで表示
    path('mark_find', views.mark_find_views, name='mark_find'),
    # mark_detailは記事の詳細画面を表示
    path('mark_detail/<int:id>', views.mark_detail_view, name='mark_detail'),
    # mark_htmlは投稿した記事をHTMLで表示できる。
    path('mark_html/<int:id>', views.mark_html_view, name='mark_html'),
    # mark_editはマークダウンでの編集画面の呼び出し
    path('mark_edit/<int:id>', views.mark_edit_views, name='mark_edit'),
    # 7/20 追加 mark_checkはeditの変更内容結果を表示する画面
    # path('mark_check/<int:id>', views.check_views, name='mark_check'),
    # 8/30 追加 mark_saveは変更を保存を行う画面
    # path('mark_save/<int:id>', views.mark_save_view, name='mark_save'),
    # 7/15 追加 my_articelは自分の記事の画面表示
    path('my_articles', views.my_articles, name='my_articles'),
    # 7/26 変更 mark_deleteViewは記事の削除を行う
    path('mark_delete/<int:id>', views.mark_delete_view, name='mark_delete'),
    # 12/21追加
    path('mark_guide', views.mark_guide_view, name='mark_guide'),
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

muscle_site/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mdeditor/',include('mdeditor.urls')),
    path('', include('muscle_app.urls')),
    
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

muscle_app/forms.py
from django import forms
from .models import Article, UsersList
from mdeditor.fields import MDTextFormField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm


# ユーザー関連
# 新規登録のフォーム
class Sign_up_Form(UserCreationForm):
    class Meta:
       model = UsersList
       fields = ("user_id", "username", "email", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['user_id'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

# ログイン画面のフォーム
class LoginForm(AuthenticationForm):
    class Meta:
       model = UsersList
       fields = ("email", "password")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
    
# ユーザー情報の変更画面のフォーム
# class UserChangeForm(forms.ModelForm):
#     class Meta:
#         model = UsersList
#         fields = ("user_id", "username", "email")



class UserChangeForm(forms.ModelForm):
    class Meta:
        model = UsersList
        fields = ("user_id", "username", "email")

    def __init__(self, user_id=None, username=None, email=None, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        # ユーザーの更新前情報をフォームに挿入
        if user_id:
            self.fields['user_id'].widget.attrs['value'] = user_id
        if username:
            self.fields['username'].widget.attrs['value'] = username
        if email:
            self.fields['email'].widget.attrs['value'] = email
            
    # def update(self, user):
    #     user.user_id = self.cleaned_data['user_id']
    #     user.username = self.cleaned_data['username']
    #     user.email = self.cleaned_data['email']
    #     user.save()

# パスワード変更画面のフォーム
class PasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

# 記事関連
# 記事につけるカテゴリのリスト
tag = (
    ("all","all"),
    ("chest","胸"),
    ("back","背中"),
    ("abs","腹"),
    ("arm","腕"),
    ("leg","脚"),
)

# 記事の新規登録画面のフォーム
class ArticleForm(forms.Form):
    # username = forms.CharField()
    title = forms.CharField ()
    content = MDTextFormField()
    category = forms.ChoiceField(choices=tag)
    #session用？の為に追加
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Article
        fields = ("user_id", "username", "title", "content", "category")

# 記事の更新画面のフォーム
class Update_ArticleForm(forms.Form):
    title = forms.CharField ()
    content = MDTextFormField()
    category = forms.ChoiceField(choices=tag)
    #session用？の為に追加
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

muscle_app/views.py
from .models import UsersList, Article
from . forms import *
from .Exceptions import ValueNoneError

from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, CreateView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.utils import DataError

from audioop import add
from email import contentmanager
from multiprocessing import context
from operator import is_
from turtle import back
from wsgiref.handlers import format_date_time

# renderに渡した文字列の中にあるHTMLタグをエスケープさせないようにするモジュール
from django.utils.safestring import mark_safe

# Create your views here.
def index_view(request):
    return render(request, "muscle_app/index.html")

# マークダウンの使い方
def mark_guide_view(request):
    return render(request, "muscle_app/mark_guide.html")

# ユーザーの新規登録処理
class SignUp(CreateView):
    def post(self, request, *args, **kwargs):
        form = Sign_up_Form(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data.get("user_id")
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password1")
            user = UsersList.objects.create(user_id=user_id, username=username, email=email)
            user.set_password(password)
            user.save()
            login(request, user, backend="muscle_app.backends.EmailAuthenticationBackend")
            return redirect('/')
        return render(request, 'muscle_app/sign_up.html', {'form': form})

    def get(self, request, *args, **kwargs):
        form = Sign_up_Form(request.POST or None)
        form.initialized = False
        return  render(request, 'muscle_app/sign_up.html', {'form': form})


# ログイン処理
class Login(View):
    def post(self, request, *args, **kwargs):
        username = request.POST["username"]
        if username.find("@") >= 0:
            if username.find("@") == 0:
                username = username[1:]
            form = LoginForm(data={"username": username, "password": request.POST["password"]})
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(request, username=username, password=password)
                if username.find("@") == -1:
                    login(request, user, "muscle_app.backends.UseridAuthenticationBackend")
                    # print("ユーザーIDでログインしたよ。")
                else:
                    login(request, user, "muscle_app.backends.EmailAuthenticationBackend")
                    # print("Emailでログインしたよ。")
                return redirect('/')

        form = LoginForm(data=request.POST)
        error = "<h3>ユーザー情報とパスワードが一致しませんでした。<br>また、UserIdでログインする場合は先頭に@を入力してください。</h3>"
        # return render(request, 'muscle_app/login.html', {'form': form, 'error': "ユーザー情報とパスワードが一致しませんでした。" + "<br>" + "また、UserIdでログインする場合は先頭に@を入力してください。"})
        return render(request, 'muscle_app/login.html', {'form': form, 'error': mark_safe(error)})

    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        return render(request, 'muscle_app/login.html', {'form': form})

# ログアウト処理
class Logout(LogoutView):
    template_name = 'logout.html'

# マイページの表示
@login_required
def mypage_view(request):
    return render(request, "muscle_app/mypage.html")

# ユーザー情報を表示
@login_required
def user_detail(request, user_id):
    # get_object_or_404の引数は、(データベース名, カラム名=変数名)で書く。pkはプライマリーキーのこと。
    user = get_object_or_404(UsersList, user_id=user_id)
    return render(request, 'muscle_app/users_detail.html', {'user': user})

# ログインしていない際の例外処理の追加が必要。
class UserUpdate(View):
    def post(self, request, *args, **kwargs):
        user = get_object_or_404(UsersList, user_id=request.user.user_id)
        form = UserChangeForm(data=request.POST, instance=user)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            return redirect("/user_detail/" + str(user.user_id))
        else:
            form = UserChangeForm(data=request.POST)
            return render(request, 'muscle_app/change.html', {'form': form})

    def get(self, request, *args, **kwargs):
        kwargs = dict(user_id=request.user.user_id, username=request.user.username, email=request.user.email)    
        form = UserChangeForm(request.POST, initial=kwargs)
        return  render(request, 'muscle_app/change.html', {'form': form})

# パスワード変更処理
class PasswordChange(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('muscle_app:password_done')
    template_name = 'muscle_app/password_change.html'

# パスワード変更完了画面を表示
class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'muscle_app/password_change_done.html'

#markdownの画面を呼び出す（新規）
@login_required
def mark_view(request):
    form = ArticleForm()
    mkdown = {'form': form}
    return render(request, "muscle_app/markdown.html", mkdown)

#保存する時の処理（保存した結果は表示しない）
@login_required
def mark_insert_view(request):
    form = ArticleForm(request.POST or None)
    user = get_object_or_404(UsersList, user_id=request.user.user_id)
    if form.is_valid():
        title = form.cleaned_data["title"]
        content = form.cleaned_data["content"]
        category= form.cleaned_data["category"]
        Article.objects.create(author=user, title=title, content=content, category=category)
    return render(request, "muscle_app/mark_insert.html", {'form': form})

#記事一覧
def mark_list_views(request):
    obj = Article.objects.all()
    content = {
        'db_list' : obj
    }
    return render(request, "muscle_app/mark_list.html", {'content_list': content})

# タグごとに記事を絞り込んで表示
def parts_view(request, category):
    partsname = {"leg": "脚", "abs": "腹部", "chest": "胸部", "back": "背中", "arm": "腕"}
    parts = Article.objects.filter(category=category)
    return render(request, "muscle_app/parts.html", {'category_list': parts, 'category': partsname[category]})

# 検索ボックスに入力されたキーワードをもとに記事を検索
def mark_find_views(request):
    word = request.POST['word']
    if word.find("@") == 0:
        obj = Article.objects.filter(author_id__user_id__icontains=word[1:])
    else:
        obj = Article.objects.filter(title__icontains=word)
    content = {
        'db_list' : obj
    }
    return render(request, "muscle_app/mark_list.html", {'content_list': content})
    
#記事の詳細
def mark_detail_view(request, id):
    # print(id)
    obj = get_object_or_404(Article, id=id)
    return render(request, "muscle_app/mark_detail.html", {'article': obj})


# デザインについてゴリラと要相談
# HTML表示の際に、どのようなデザインにするか。また、user_idや、usernameなどを表示するかなど。
# ID指定の表示
def mark_html_view(request, id):
    obj = get_object_or_404(Article, id=id)
    content = {
        'author': obj.author_id,
        'title' : obj.title,
        'content' : obj.content,
        'category': obj.category,
    }
    return render(request, "muscle_app/mark_view.html", {'db_view':content, 'article':obj})

# 記事の編集
def mark_edit_views(request, id):
    #modelのデータを持ってくる
    article = get_object_or_404(Article, id=id)
    update_form = {"title": article.title, "content":article.content, "category":article.category}
    form = Update_ArticleForm(request.POST or update_form)
    if request.POST:
        try:
            if form.is_valid():
                #.cleaned_dataは.is_valid()がtrueだった場合に,正しかったデータが入る
                article.title = form.cleaned_data["title"]
                article.content = form.cleaned_data["content"]
                article.category = form.cleaned_data["category"]
                article.save()
                obj = Article.objects.filter(author_id__user_id=request.user.user_id)
                content = {
                    'db_list' : obj
                }
                return render(request, "muscle_app/my_article.html", {'content_list':content})

            else:
                if request.POST["title"].isspace or request.POST["content"].isspace:
                    raise ValueNoneError("タイトル、またはコンテンツが入力されていません。")
                else :
                    redirect('muscle_app:mark_list')

        except DataError:
            ctx = { "update_form": form }
            ctx["object"] = article
            ctx["error"] = '入力内容が不正です。'
            return render(request, "muscle_app/mark_edit.html", ctx)

        except ValueNoneError as e:
            ctx = { "update_form": form }
            ctx["object"] = article
            ctx["error"] = e
            return render(request, "muscle_app/mark_edit.html", ctx)

    else:
        #ctxに辞書型を挿入することでrenderの見た目と拡張性が上がるはず
        ctx = { "update_form": form }
        ctx["object"] = article
       
    return render(request, "muscle_app/mark_edit.html", ctx)

# ログインしたユーザーの記事だけ表示処理
def my_articles(request):
    obj = Article.objects.filter(author_id__user_id=request.user.user_id)
    content = {
        'db_list' : obj
    }
    return render(request, "muscle_app/my_article.html", {'content_list': content})
    
# ログインしていない際の例外処理が必要
# 記事の削除処理
def mark_delete_view(request, id):
    obj = get_object_or_404(Article, id=id)
    if request.user.user_id == obj.author.user_id:
        ctx = {"object": obj}
        if request.POST:
            obj.delete()
            return redirect("muscle_app:mark_insert")
        return render(request, "muscle_app/mark_delete.html", ctx)

    else:
        obj = Article.objects.all()
        content = {
            'db_list' : obj
        }
        return render(request, "muscle_app/mark_list.html", {'content_list': content, 'error': "投稿者以外消せねーよばーか"})

templates/muscle_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'muscle_app/header.css' %}">
        <!-- この中にCSSなどを指定。 -->
        {% block extra_head %}
        {% endblock %}
        <title>
            <!-- この中は継承先で定義 -->
            {% block title_block %}
            {% endblock %}
        </title>
    </head>
    <body>
        <div class="wrapper">
            <header>
                <div class="top_wrapper">
                    <div class="top_left_wrapper">
                            <a class="logo" href="{% url 'muscle_app:index' %}"><img src="/static/img/susie_nick.png" alt="ロゴ画像"></a>
                    </div>
                    <div id="globalnavi">
                        <!-- <div class="navi"> -->
                        <ul class="dropmenu">
                          <li><a href="{% url 'muscle_app:index' %}"><h2>Top</h2></a></li>
                          <li class="men"><a href=""><h2>Training</h2></a>
                            <ul>
                              <li><a href="{% url 'muscle_app:mark_list' %}">All</a></li>
                              <li><a href="{% url 'muscle_app:parts' 'leg' %}">Leg</a></li>
                              <li><a href="{% url 'muscle_app:parts' 'abs' %}">Abs</a></li>
                              <li><a href="{% url 'muscle_app:parts' 'chest' %}">Chest</a></li>
                              <li><a href="{% url 'muscle_app:parts' 'back' %}">Back</a></li>
                              <li><a href="{% url 'muscle_app:parts' 'arm' %}">Arm</a></li>
                            </ul>
                          </li>
                    </div>
                    <div class="serch">
                        <form id="form1" action="" method="get">
                            <input id="sbox1" type="search" name="search" placeholder="検索キーワードを入力">
                            <input id="sbtn1" type="submit" name="submit" value="検索">
                        </form>
                    </div>

                    <div class="login">
                        {% if user.is_authenticated %}
                            <p>{{ user.get_username }}でログイン中</p>
                            <button class="mypagebtn" onclick=location.href="{% url 'muscle_app:mypage' %}">マイページ</button>
                            <button class="logoutbtn"onclick=location.href="{% url 'muscle_app:logout' %}">ログアウトする</button>
                        {% else %}
                        <p>ログインしていません</p>
                        <!-- <button class="btn btn-flat" onclick=location.href="{% url 'muscle_app:login' %}">ログイン</button> -->
                        <a href="{% url 'muscle_app:login' %}" class="btn btn-flat"><span>ログイン</span></a>
                        <!-- ログインボタンの後に新規作成を追加するか検討
                        <button onclick=location.href="{% url 'muscle_app:sign_up' %}">新規登録</button> -->
                        {% endif %}
                        <!-- {}の最初と最後に%を付けると有効になる。 -->
                        <!-- <button onclick="">ログイン</button> -->
                        <!-- <button onclick="">ログアウト</button> -->
                    </div>
                </div>
              </header>
              
            {% block body_block %}
            <!-- この中は継承先で定義 -->
            {% endblock %}
        </div>
    </body>
</html>

templates/muscle_app/base1.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'muscle_app/reset.css' %}">
        <link rel="stylesheet" href="{% static 'muscle_app/header1.css' %}">
        <script type="text/javascript" src="{% static 'js/drop.js' %}"></script>
        
        <!-- この中にCSSなどを指定。 -->
        {% block extra_head %}
        {% endblock %}
        <title>
            <!-- この中は継承先で定義 -->
            {% block title_block %}
            {% endblock %}
        </title>
    </head>
    <body>
        <header class="header01">
                <a class="header01-logo" href="{% url 'muscle_app:index' %}"><img class="sitelogo" src="/static/img/susie_nick.png" width="140px" alt="ロゴ画像"></a>
                <nav class="header01-nav">
                <ul class="header01-lists">
                    <li>
                        <a href="{% url 'muscle_app:index' %}"><h2>Top</h2></a>
                    </li>
                    <li class="men"><a href=""><h2>Training</h2></a>
                        <ul>
                          <li><a href="{% url 'muscle_app:mark_list' %}"><img class="icon" src="/static/img/mypage.png">Mypage</a></li>
                          <li><a href="{% url 'muscle_app:parts' 'leg' %}"><img class="icon" src="/static/img/asi.png">Leg</a></li>
                          <li><a href="{% url 'muscle_app:parts' 'abs' %}"><img class="icon" src="/static/img/hukkin.png">Abs</a></li>
                          <li><a href="{% url 'muscle_app:parts' 'chest' %}"><img class="icon" src="/static/img/kyoukin.png">Chest</a></li>
                          <li><a href="{% url 'muscle_app:parts' 'back' %}"><img class="icon" src="/static/img/haikin.png">Back</a></li>
                          <li><a href="{% url 'muscle_app:parts' 'arm' %}"><img class="icon" src="/static/img/Arm.jpeg">Arm</a></li>
                        </ul>
                    </li>
                </ul>

                    <ul class="header01-lists">
                        <li class="serch">
                            <form id="form1" action="" method="get">
                                <input id="sbox1" type="search" name="search" placeholder="検索キーワードを入力">
                                <input id="sbar1" type="submit" name="submit" value="検索">
                            </form>
                        </li>
                    {% if user.is_authenticated %}
                        <p>{{ user.get_username }}でログイン中</p>
                        <div id="trim">
                            <ul class="dropdown">
                                <li><a class="dropdown_btn" id="dropdown_btn"><img src="/static/img/muscle_risu.png" width="140px"></a>
                                        <ul id="dropdown_list" style="display: none;">
                                            <li><a href="{% url 'muscle_app:mypage' %}">マイページ</a></li>
                                            <li><a href="{% url 'muscle_app:mark' %}">記事作成</a></li>
                                            <li><a href="{% url 'muscle_app:logout' %}">ログアウト</a></li>
                                        </ul>
                                </li>
                            </ul>
                        </div>
                    {% else %}
                        <li>
                            <button class="btn slide-bg" onclick=location.href="{% url 'muscle_app:login' %}" >ログイン</button>
                        </li>
                    {% endif %}
                    </ul>
                </nav>
        </header>

        {% block body_block %}
        <!-- この中は継承先で定義 -->
        {% endblock %}
    </body>
</html>

templates/muscle_app/mark_list.html
{% extends "muscle_app/base1.html" %}
{%load static%}

<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />
    </head>
    {% block body_block %}
    <body>
    <h1>記事一覧画面</h1>
    <h1>{{ error }}</h1>
    <button onclick=location.href="{% url 'muscle_app:mark' %}">新規作成</button>
    {% csrf_token %}
    <form  method="get">
        {% for article in content_list.db_list%}
            <a href="{% url 'muscle_app:mark_html' id=article.id %}">
                <span>@{{ article.author.user_id }}</span>
                {{ article.author.username }}
                {{ article.title }} 
                {{ article.category }}<br>
            </a>
            <input type="hidden" value="{{article.id}}"> 
        {% endfor %}
        </form>
        <button onclick=location.href="{% url 'muscle_app:index' %}">戻る</button>
    </body>
    {% endblock %}
</html>

templates/muscle_app/my_article.html
<!-- 使用していません。 -->
{% extends "muscle_app/base1.html" %}

{%load static%}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <meta http-equiv = "Content-Type" content = "text / html; charset = utf-8" />
    </head>
    {% block body_block %}
    <body>
        {% comment %} 現在markで作成したユーザー名を表示している {% endcomment %}
        {% comment %} 自分の作業作成された記事の表示かつ自分のもの限定 {% endcomment %}
        <h1>@{{ user.user_id }}の記事一覧</h1>   
        {% csrf_token %}
        {% for article in content_list.db_list %}
        <form  method="get">
            <a href="{% url 'muscle_app:mark_html' id=article.id %}">
                <span>@{{ article.author.user_id }}</span>
                {{ article.author.username}}
                {{ article.title }} 
                {{ article.category }}
            </a>
            {% comment %} <button type="button">編集する</button><br> {% endcomment %}
            <button type="button" onclick=location.href="{% url 'muscle_app:mark_edit' id=article.id %}">編集画面へ</button>
            <button type="button" onclick=location.href="{% url 'muscle_app:mark_delete' id=article.id %}">削除する</button><br>
        {% endfor %}
        <button type="button" onclick=location.href="{% url 'muscle_app:mypage' %}">戻る</button>
    </body>
    {% endblock %}
</html>

templates/muscle_app/my_detail.html
{% extends "muscle_app/base1.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>記事詳細</title>
</head>
<body>
    <form action="{% url 'muscle_app:mark_edit' %}" method="post" >
    {% csrf_token %}
    {{ article.username }}
    {{ article.title }} 
    {{ article.content }}
    <input type="hidden" value="{{ article.id }}" name='id'> 
    <p><input type = "submit" value = "編集画面へ移動する"></p>
    </form>
    <button type="button" onclick=location.href="{% url 'muscle_app:mypage' %}">戻る</button>
</body>
</html>

templates/muscle_app/parts.html
<!DOCTYPE html>
<html lang="ja">
    {% extends "muscle_app/base1.html" %}
    {% load static %}

    {% block extra_head %}
        <link rel="stylesheet" href="{% static '' %}">
    {% endblock %}
    
    {% block title_block %}
        leg
    {% endblock %}

    {% block body_block %}
        <h1>{{ category }}</h1>
        <form  method="get">
            {% for article in category_list %}
                <a href="{% url 'muscle_app:mark_html' id=article.id %}">
                    <span>@{{ article.author.user_id }}</span>
                    {{ article.author.username }}
                    {{ article.title }} 
                    {{ article.category }}<br>
                </a>
                {% comment %} <button type="button">編集する</button><br> {% endcomment %}
            {% endfor %}
        <form>
    <button type="button" onclick=location.href="{% url 'muscle_app:index' %}">戻る</button>  
    {% endblock %}
</html>

templates/muscle_app/users_detail.html
{% extends "muscle_app/base1.html" %}

{% block body_block %}
<p>ユーザーID:</p>
<p>@{{ user.user_id }}</p>
<br>
<p>ユーザーネーム:</p>
<p>{{ user.username }}</p>
<br>
<p>メールアドレス:</p>
<p>{{ user.email }}</p>
<br>
<p>パスワード:</p>
<h1>ないしょ！！！！！！！</h1>
<br>
<button onclick=location.href="{% url 'muscle_app:user_update' %}">ユーザー情報変更はこちらから</button><br>
<button onclick=location.href="{% url 'muscle_app:password_change' %}">パスワードの変更はこちらから</button><br>
<button onclick=location.href="{% url 'muscle_app:mypage' %}">マイページに戻る</button><br>
{% endblock %}